### ISSUE TITLE
Script not working. Unhandled 'error' event

### ISSUE THREAD

**Issue by Arttse** [riobard/font-awesome-svg#2]
``` sh
# Step 1. Install module globally
$ sudo npm -g i font-awesome-svg

# Step 2. CLI Usage.
$ fa2svg --dir ./fa-svg --verbose
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'charCodeAt' of undefined
    at /usr/local/lib/node_modules/font-awesome-svg/node_modules/svgfont2js/index.js:56:39
    at Parser.<anonymous> (/usr/local/lib/node_modules/font-awesome-svg/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (/usr/local/lib/node_modules/font-awesome-svg/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/usr/local/lib/node_modules/font-awesome-svg/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/usr/local/lib/node_modules/font-awesome-svg/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/usr/local/lib/node_modules/font-awesome-svg/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/usr/local/lib/node_modules/font-awesome-svg/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/font-awesome-svg/node_modules/xml2js/lib/xml2js.js:508:31)
```
## 

Node.js 6.9.1
NPM 3.10.9
Linux Ubuntu 16.04

**Comment by Arttse** [comment]
Problem resolved in PR riobard/svgfont2js#2
Need to merge it and publish new version.
